ECB:
	./encrypt2.py ECB 16sizeKeyowskvid linux.jpeg opgg_ECB_c.png
	./decrypt2.py ECB 16sizeKeyowskvid opgg_ECB_c.png opgg_ECB_p.png
CBC:
	./encrypt2.py CBC 16sizeKeyowskvid linux.jpeg opgg_CBC_c.png
	./decrypt2.py CBC 16sizeKeyowskvid opgg_CBC_c.png opgg_CBC_p.png
